version: '3.8'
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: ches/kafka
    hostname: localhost
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      ZOOKEEPER_IP: zookeeper