version: '3.8'

services: 
    proxy:
        image: nginx:alpine
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        restart: always
        depends_on: 
            - app1
            - app2
            - app3
            - app4
    app1:
        image: nodeapp
        ports: 
            - 2222:9999
        environment: 
            - APP_ID=101
    app2:
        image: nodeapp
        ports: 
            - 3333:9999
        environment: 
            - APP_ID=205
    app3:
        image: nodeapp
        ports: 
            - 4444:9999
        environment: 
            - APP_ID=306
    app4:
        image: nodeapp
        ports: 
            - 5555:9999
        environment: 
            - APP_ID=409